version: "3"
services:
  nginx:
    build:
      context: infrastructure/local/nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  frontend:
    build:
      context: .
      dockerfile: infrastructure/local/node/Dockerfile
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
    - .:/home/node/app
    command: "yarn run start"