version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: sarah-app/prod
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f infrastructure/prod/nginx/Dockerfile .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.digitalocean.com/dfs-docr
            docker tag $IMAGE_NAME registry.digitalocean.com/dfs-docr/$IMAGE_NAME:latest
            docker push registry.digitalocean.com/dfs-docr/$IMAGE_NAME:latest
workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build:
          filters:
            branches:
              only: master